/**
 * Decision Logging for swarm-cli
 * 
 * Writes decisions to SWARM_LOG.md in the repo for tracking
 * what agents were used, conflicts found, and decisions made.
 */

import { writeFile, readFile, appendFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { SynthesisResult, FileConflict } from './types.js';

export interface DecisionEntry {
  filePath: string;
  choice: string;
  agentName?: string;
  customInput?: string;
  timestamp: string;
}

export interface SwarmLogEntry {
  timestamp: string;
  task: string;
  repoPath: string;
  agents: string[];
  synthesizer: string;
  duration: number;
  agentResults: {
    name: string;
    success: boolean;
    filesChanged: number;
  }[];
  conflicts: {
    filePath: string;
    severity: string;
    type: string;
  }[];
  decisions: DecisionEntry[];
  applied?: {
    agent: string;
    method: string;
    files: string[];
  };
}

const LOG_FILE = 'SWARM_LOG.md';
const LOG_SEPARATOR = '\n---\n\n';

/**
 * Write a swarm session log entry
 */
export async function writeSwarmLog(
  repoPath: string,
  entry: SwarmLogEntry
): Promise<void> {
  const logPath = join(repoPath, LOG_FILE);
  const content = formatLogEntry(entry);

  if (existsSync(logPath)) {
    // Prepend to existing log (newest first)
    const existing = await readFile(logPath, 'utf-8');
    await writeFile(logPath, content + LOG_SEPARATOR + existing, 'utf-8');
  } else {
    // Create new log file
    const header = `# SWARM Log

This file tracks swarm-cli sessions, decisions, and applied changes.
Generated by [swarm-cli](https://github.com/yourrepo/swarm-cli).

---

`;
    await writeFile(logPath, header + content, 'utf-8');
  }
}

/**
 * Format a log entry as markdown
 */
function formatLogEntry(entry: SwarmLogEntry): string {
  const lines: string[] = [];

  // Header
  lines.push(`## ${formatDate(entry.timestamp)}`);
  lines.push('');

  // Task
  lines.push(`**Task:** ${entry.task}`);
  lines.push('');

  // Configuration
  lines.push('### Configuration');
  lines.push('');
  lines.push(`- **Agents:** ${entry.agents.join(', ')}`);
  lines.push(`- **Synthesizer:** ${entry.synthesizer}`);
  lines.push(`- **Duration:** ${(entry.duration / 1000).toFixed(1)}s`);
  lines.push('');

  // Agent Results
  lines.push('### Agent Results');
  lines.push('');
  lines.push('| Agent | Status | Files Changed |');
  lines.push('|-------|--------|---------------|');
  for (const result of entry.agentResults) {
    const status = result.success ? '✅ Success' : '❌ Failed';
    lines.push(`| ${result.name} | ${status} | ${result.filesChanged} |`);
  }
  lines.push('');

  // Conflicts
  if (entry.conflicts.length > 0) {
    lines.push('### Conflicts');
    lines.push('');
    lines.push('| File | Severity | Type |');
    lines.push('|------|----------|------|');
    for (const conflict of entry.conflicts) {
      const severity = {
        high: '🔴 High',
        medium: '🟡 Medium',
        low: '🟢 Low',
      }[conflict.severity] || conflict.severity;
      lines.push(`| \`${conflict.filePath}\` | ${severity} | ${formatConflictType(conflict.type)} |`);
    }
    lines.push('');
  }

  // Decisions
  if (entry.decisions.length > 0) {
    lines.push('### Decisions');
    lines.push('');
    for (const decision of entry.decisions) {
      if (decision.choice === 'skip') {
        lines.push(`- **\`${decision.filePath}\`**: ⏭️ Skipped`);
      } else if (decision.choice === 'custom') {
        lines.push(`- **\`${decision.filePath}\`**: 📝 Custom: "${decision.customInput}"`);
      } else if (decision.agentName) {
        lines.push(`- **\`${decision.filePath}\`**: Used ${decision.agentName}'s changes`);
      }
    }
    lines.push('');
  }

  // Applied changes
  if (entry.applied) {
    lines.push('### Applied Changes');
    lines.push('');
    lines.push(`- **Method:** ${entry.applied.method}`);
    lines.push(`- **Agent:** ${entry.applied.agent}`);
    lines.push(`- **Files:** ${entry.applied.files.join(', ')}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Format ISO date to readable string
 */
function formatDate(isoDate: string): string {
  const date = new Date(isoDate);
  return date.toLocaleString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Format conflict type for display
 */
function formatConflictType(type: string): string {
  return type.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

/**
 * Create a commit message including swarm decisions
 */
export function createCommitMessage(
  task: string,
  decisions: DecisionEntry[],
  mainAgent?: string
): string {
  const lines: string[] = [];

  // First line - summary
  if (mainAgent) {
    lines.push(`swarm: Apply ${mainAgent} changes - ${truncate(task, 50)}`);
  } else {
    lines.push(`swarm: ${truncate(task, 60)}`);
  }
  lines.push('');

  // Body
  lines.push('Changes applied via swarm-cli multi-agent deliberation.');
  lines.push('');

  if (decisions.length > 0) {
    lines.push('Decisions:');
    for (const d of decisions) {
      if (d.agentName) {
        lines.push(`- ${d.filePath}: ${d.agentName}`);
      } else if (d.choice === 'custom') {
        lines.push(`- ${d.filePath}: custom`);
      }
    }
  }

  return lines.join('\n');
}

/**
 * Truncate string with ellipsis
 */
function truncate(str: string, length: number): string {
  if (str.length <= length) return str;
  return str.slice(0, length - 3) + '...';
}

export default { writeSwarmLog, createCommitMessage };
